services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: english_growth
      POSTGRES_USER: english_user
      POSTGRES_PASSWORD: english_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend

    env_file:
      - .env

    environment:
      - OPENAI_API_KEY=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
      - DATABASE_URL=postgresql+psycopg2://english_user:english_password@db:5432/english_growth

    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

    volumes:
      - ./backend:/app

    ports:
      - "8000:8000"

    depends_on:
      - db

volumes:
  postgres_data: